{% set version = "0.2.1" %}
{% set build = 0 %}

package:
  name: fabmos
  version: {{ version }}

source:
  #git_url: https://github.com/BoldingBruggeman/fabmos.git
  url: https://github.com/BoldingBruggeman/fabmos/releases/download/v{{ version }}/fabmos.tar.gz
  sha256: ad1db129c0a3565525cac7b35745717f3597a02b1510975229a289ae26922863

build:
  number: {{ build }}
  #skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make                                   # [not win]
    - {{ compiler('fortran') }}              # [not win]
    - {{ stdlib("c") }}                      # [not win] on Windows this pulls in VS and causes cmake to use its cl.exe, which is incompatible with the m2w64 version of windres.exe
    #- {{ compiler('m2w64_fortran') }}        # [win]
    #- {{ stdlib("m2w64_c") }}                # [win]
    - {{ compiler('c') }}                    # [win] to locate msvc
    #- {{ stdlib("c") }}                      # [win]
  host:
    - python {{ python }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - xarray
    - mpi4py
    - netCDF4
    - pygetm >=0.9
    - scipy
    - h5py
    #- m2w64-gcc-libgfortran      # [win] NB m2w64-gcc-libs and m2w64-gcc-libs-core are added automatically by m2w64 compiler functions under build

test:
  imports:
    - fabmos

about:
  home: https://github.com/BoldingBruggeman/fabmos
  summary: 'FABM offline simulator'
  description: |
    Offline simulator for the Framework for Aquatic Biogeochemical Models
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/BoldingBruggeman/fabmos/wiki

extra:
  recipe-maintainers:
    - jornbr
